name: 🏗️ Setup Environment
description: Install Dependencies & Deploy Workarounds

inputs:
  os:
    required: true
    description: Operating System used

runs:
  using: "composite"

  steps:
    - name: 🩹 Enable Long Paths
      shell: bash
      if: ${{ inputs.os == 'windows-latest' }}
      run: git config --system core.longpaths true

    - name: 🖥️ Enable MSVC Dev Console
      uses: ilammy/msvc-dev-cmd@v1

    - name: 📋 Install OpenMP
      shell: bash
      if: ${{ inputs.os == 'macos-latest' }}
      run: |
        brew install libomp
        echo "OpenMP_ROOT=$(brew --prefix)/opt/libomp" >> $GITHUB_ENV

    - name: 💻 Setup Deployment Target
      shell: bash
      if: ${{ inputs.os == 'macos-latest' }}
      run: |
        echo "MACOSX_DEPLOYMENT_TARGET=14.0" >> $GITHUB_ENV
