name: ðŸ—ï¸ Setup Environment
description: Install Dependencies & Deploy Workarounds

inputs:
  container:
    required: true
    description: Build container used

  install-vtk:
    required: true
    description: Wether or not to install VTK as a system dependency

runs:
  using: "composite"

  steps:
    - name: ðŸ©¹ Enable Long Paths
      shell: bash
      if: ${{ inputs.container == 'windows-latest' }}
      run: git config --system core.longpaths true

    - name: ðŸ–¥ï¸ Enable MSVC Dev Console
      uses: ilammy/msvc-dev-cmd@v1

    - name: ðŸ“‹ Install Dependencies
      shell: bash
      if: ${{ inputs.container == 'ubuntu-latest' }}
      run: dnf install -y gcc gcc-c++ kernel-devel cmake ninja-build git docker sed clang-tools-extra

    - name: ðŸ“‹ Install OpenMP
      shell: bash
      if: ${{ inputs.container == 'macos-latest' }}
      run: |
        brew reinstall --build-from-source --formula ./.github/homebrew/libomp.rb
        echo "OpenMP_ROOT=$(brew --prefix)/opt/libomp" >> $GITHUB_ENV

    - name: ðŸ“‹ Install VTK
      shell: bash
      if: ${{ inputs.install-vtk == 'true' }}
      run: dnf install -y vtk vtk-devel
